### ISSUE TITLE
Running APE with Wildfly Swarm example throws an exception

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-extension-persistence#52]
Running APE with Wildfly Swarm throws an exception.

The exception is 

```
ava.lang.IllegalStateException: No org.jboss.arquillian.container.test.spi.command.CommandService found in context

	at org.jboss.arquillian.persistence.core.container.CommandServiceProducer.createCommandService(CommandServiceProducer.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.jboss.arquillian.junit.container.JUnitTestRunner.execute(JUnitTestRunner.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wildfly.swarm.arquillian.daemon.TestRunner.executeTest(TestRunner.java:64)
	at org.wildfly.swarm.arquillian.daemon.server.Server.executeTest(Server.java:241)
```

And the project can be found https://github.com/lordofthejars/swarm-ape

According to stacktrace, whatI think it is happening is that Arquillian Daemon does not implement any CommandService to communicate with client side, and this is something required by APE.

**Comment by lordofthejars** [comment]
It should be implemented a CommandService https://github.com/arquillian/arquillian-daemon/blob/master/protocol-arquillian/src/main/java/org/jboss/arquillian/daemon/protocol/arquillian/DaemonProtocol.java
